/** Materials */
export const AC_SAVE_MATERIAL = 'AC_SAVE_MATERIAL'
export const AC_UPDATE_MATERIAL = 'AC_UPDATE_MATERIAL'
export const AC_DELETE_MATERIAL = 'AC_DELETE_MATERIAL'
export const MT_SAVE_MATERIAL = 'MT_SAVE_MATERIAL'
export const MT_UPDATE_MATERIAL = 'MT_UPDATE_MATERIAL'
export const MT_DELETE_MATERIAL = 'MT_DELETE_MATERIAL'

/** Foods */
export const AC_SAVE_FOOD = 'AC_SAVE_FOOD'
export const AC_UPDATE_FOOD = 'AC_UPDATE_FOOD'
export const AC_DELETE_FOOD = 'AC_DELTE_FOOD'
export const MT_SAVE_FOOD = 'MT_SAVE_FOOD'
export const MT_UPDATE_FOOD = 'MT_UPDATE_FOOD'
export const MT_DELETE_FOOD = 'MT_DELETE_FOOD'

/** Recipe */
export const MT_UPDATE_RECIPE = 'UPDATE_RECIPE'

/** Composition */
export const MT_UPDATE_COMPOSITION = 'UPDATE_COMPOSITION'